### ISSUE TITLE
Extend Digital Twin to Other Platforms

### ISSUE THREAD

**Issue by tderflinger** [team-watchdog/colombo-skylines#1]
Hi!

Very cool work, this looks really good. What I am wondering, would it be feasible to use your data in a game engine like Godot or Babylon.js to offer your great work to everybody?

What I mean, now if somebody wants to enjoy your digital twin city they have to buy the game. But with the alternative platforms like Babylon.js, they would only need a web browser. So everybody could see your work and walk through the digital city.

Would this be something that is possible (in terms of data format, etc.)?

Thanks and keep up the good work!

-Thomas

**Comment by yudhanjaya** [comment]
Thanks!

Unfortunately, that’s not possible right now. Godot is cool, but for this
to work we would have to replicate the entire game engine of Skylines -
because that’s where not just the placement, but all the simulation
components are handled.

**Comment by tderflinger** [comment]
I see, that's a pity. Thanks anyways for your fast reply!
